from knotis.contrib.denormalize.tests import *
from knotis.contrib.auth.tests import *
from knotis.contrib.identity.tests import *
from knotis.contrib.relation.tests import *
from knotis.contrib.inventory.tests import *
from knotis.contrib.product.tests import *
from knotis.contrib.offer.tests import *
from knotis.contrib.transaction.tests import *
from knotis.contrib.legacy.tests import *
