from django.conf.urls.defaults import patterns, url


urlpatterns = patterns(
    'legacy.views',
    url(
        r'^deals/$',
        'map_redirect'
    ),
    url(
        r'^category/contact/$',
        'map_redirect'
    ),
    url(
        r'^home/account/$',
        'map_redirect'
    ),
    url(
        r'^home/login/$',
        'map_redirect'
    ),
    url(
        r'^backend/user/$',
        'map_redirect'
    ),
    url(
        r'^backend/$',
        'map_redirect'
    ),
    url(
        r'^category/page/12/$',
        'map_redirect'
    ),
    url(
        r'^category/page/14/$',
        'map_redirect'
    ),
    url(
        r'^category/page/27/$',
        'map_redirect'
    ),
    url(
        r'^category/page/22/$',
        'map_redirect'
    ),
    url(
        r'^category/page/26/$',
        'map_redirect'
    ),
    url(
        r'^category/terms_of_use/$',
        'map_redirect'
    ),
    url(
        r'^category/privacy_policy/$',
        'map_redirect'
    ),
    url(
        r'^deals/city/(?P<city_name>[a-zA-Z]+)(/(?P<neighborhood_name>[a-zA-Z]+))?/$',
        'offer_city_filter_redirect'
    ),
    url(
        r'^business/profile/(?P<legacy_business_id>[\d]+)/$',
        'business_profile_redirect'
    ),
    url(
        r'^business/(?P<legacy_business_id>[\d]+)/$',
        'qrcode_redirect'
    ),
    url(
        r'^deal/profile/(?P<legacy_offer_id>[\d]+)/$',
        'offer_profile_redirect'
    )
)
